### ISSUE TITLE
IE11 Text visible on screen

### ISSUE THREAD

**Issue by digitaljohn** [techniq/react-svg-text#4]
It appears when used inside IE11 the text element you use for measuring text size remains visible on the page, e.g.

![image](https://user-images.githubusercontent.com/1425921/75191586-8348bc80-574a-11ea-8e1e-ea39fe46f66e.png)

My temporary fix is just setting the style, e.g.

```css
#__react_svg_text_measurement_id{
  opacity: 0;
}
```

This element should be removed after measurement is complete?
